#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = 'vim-monokai-tasty'
    colorscheme_bg = 'dark'
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = 'arrow'
    statusline_iseparator = 'arrow'
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    custom_color_palette = [
        ["#262626", "#A4E400", 235, 148],  # window id
        ["#BCBCBC", "#5F5F5F", 250, 236],  # statusline sections
        ["#A4E400", "#303030", 148, 236],  # statusline sections
        ["#262626", 235],                  # empty sections
        ["#262626", "#E7DC6D", 235, 228],  # window id in insert mode
        ["#262626", "#AC7CFF", 235, 141],  # window id in visual mode
        ["#262626", "#FC1A70", 235, 197],  # window id in select mode
        ["#262626", "#E7DC6D", 235, 228],  # window id in iedit-insert mode
        ["#262626", "#A4E400", 235, 148],  # window id in iedit-normal mode
    ]

    bootstrap_before = 'myspacevim#before'
    boostrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = 'complete'
auto_completion_tab_key_behavior = 'smart'

[[layers]]
name = 'checkers'
lint_on_the_fly = true

[[layers]]
name = 'debug'

[[layers]]
name = 'edit'

[[layers]]
name = 'foldsearch'

[[layers]]
name = 'format'

[[layers]]
name = 'git'

[[layers]]
name = 'github'

[[layers]]
name = 'gtags'

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#go'
enabled_linters = ['golangci_lint']
format_on_save = true

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#sh'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#vue'

[[layers]]
name = 'lang#WebAssembly'

[[layers]]
name = 'lang#xml'

[[layers]]
name = 'lsp'
enabled_clients = [
  'bashls',
  'dockerls',
  'emmet_ls',
  'golangci_lint_ls',
  'gopls',
  'graphql',
  'html',
  'jedi_language_server',
  'jsonls',
  'prismals',
  'pylsp',
  'pyre',
  'pyright',
  'sqlls',
  'sqls',
  'tailwindcss',
  'terraform_lsp',
  'terraformls',
  'tflint',
  'tsserver',
  'vimls',
  'vuels',
  'yamlls'
]

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'ssh'

[[layers]]
name = 'sudo'

[[layers]]
name = 'test'

[[layers]]
name = 'tmux'

[[layers]]
name = 'tools'

[[layers]]
name = 'treesitter'

[[layers]]
name = 'VersionControl'

[[custom_plugins]]
repo = 'm-pilia/vim-pkgbuild'
merged = false

[[custom_plugins]]
repo = 'patstockwell/vim-monokai-tasty'
merged = false
